name: final_project_of_mobile_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^3.0.0
  animations: ^2.0.11
  flutter_barcode_scanner: ^2.0.0
  video_player: ^2.9.1

  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7

  cupertino_icons: ^1.0.2
  flutter_lints: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/artists/
    - assets/images/developer/
    - assets/images/podcasts/
    - assets/images/developer/
    - assets/images/home/
    - assets/images/chill/
    - assets/images/drake mix/
    - assets/images/upbeat/
    - assets/images/2010/
    - assets/video/

  fonts:
    - family: AM
      fonts:
        - asset: fonts/Avenir Medium.ttf

    - family: AB
      fonts:
        - asset: fonts/Avenir Next LT Pro Bold.otf